import{hydrate,subscribe,getState}from"./state.js";import{initRouter,navigate}from"./router.js";
const NAV=[["start","⌂","Start"],["recipes","◒","Receptury"],["shopping","□","Zakupy"],["inventory","▦","Magazyn"],["settings","⚙","Ustawienia"]];
const ACTIONS=[["recipes","🍽️","Receptury","Przeglądaj i prowadź receptury."],["cooking","🔥","Gotowanie","Uruchom recepturę krok po kroku."],["shopping","🛒","Zakupy","Twórz listę i odhaczaj produkty."],["inventory","📦","Magazyn","Pilnuj stanów i końcówek."],["calculators","◈","Kalkulatory","Pizza, koszt i proporcje."],["settings","⚙️","Ustawienia","Wygląd, dane i preferencje."]];
const app=document.querySelector("#app");
function screenContent(route,state){
 if(route==="start")return '<section class="screen"><div class="start-hero"><div class="section-kicker">Kuchnia pod ręką</div><h1>Gotuj.<br>Ogarniaj.<br>Nie szukaj.</h1><p class="screen-lead">Kucharzyna powstaje od nowa jako szybkie, prywatne narzędzie do pracy na iPhonie.</p></div><div class="action-grid">'+ACTIONS.map(([id,icon,title,copy])=>'<button class="action-card" data-route="'+id+'" type="button"><span class="action-icon">'+icon+'</span><span><span class="action-title">'+title+'</span><span class="action-copy">'+copy+'</span></span></button>').join("")+'</div></section>';
 const titles={recipes:["Receptury","Twoje receptury i sposób pracy z nimi."],cooking:["Gotowanie","Aktywne gotowanie krok po kroku."],shopping:["Zakupy","Lista zakupów z miejscem na automatyczne pozycje z receptur."],inventory:["Magazyn","Stany produktów i kontrola końcówek."],calculators:["Kalkulatory","Narzędzia do codziennej pracy w kuchni."],settings:["Ustawienia","Preferencje aplikacji i dane."]};
 const [title,lead]=titles[route];const count=route==="recipes"&&state.recipes.length?'<h2>Masz '+state.recipes.length+' receptur</h2>':'<h2>Moduł gotowy na dane</h2>';
 return '<section class="screen"><div class="start-hero"><div class="section-kicker">Kucharzyna</div><h1 class="screen-title">'+title+'</h1><p class="screen-lead">'+lead+'</p></div><div class="empty-state">'+count+'<p>Ten ekran korzysta z nowej, czystej architektury. Kolejne funkcje dokładamy bez warstw starego kodu.</p></div></section>';
}
function render(state){const route=state.route;app.innerHTML='<header class="app-topbar"><div class="brand"><div class="brand-mark" aria-hidden="true">K</div><div class="brand-title">Kucharzyna</div></div><button class="topbar-action" type="button" data-route="settings" aria-label="Ustawienia">⚙️</button></header><main class="app-scroll" id="main-scroll">'+screenContent(route,state)+'</main><nav class="app-bottom-nav" aria-label="Główna nawigacja">'+NAV.map(([id,icon,label])=>'<button class="nav-item '+(route===id?"active":"")+'" data-route="'+id+'" type="button"><span class="nav-icon" aria-hidden="true">'+icon+'</span><span class="nav-label">'+label+'</span></button>').join("")+'</nav>';app.querySelectorAll("[data-route]").forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.route)))}
async function boot(){await hydrate();subscribe(render);initRouter(()=>render(getState()));if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{})}
boot().catch(error=>{console.error(error);app.innerHTML='<main class="app-scroll"><section class="screen"><div class="empty-state"><h2>Nie udało się uruchomić Kucharzyny</h2><p>Odśwież aplikację.</p></div></section></main>'});