const{defineConfig,devices}=require("@playwright/test");
module.exports=defineConfig({
 testDir:"./tests",
 timeout:30000,
 expect:{timeout:7000},
 fullyParallel:false,
 workers:1,
 retries:process.env.CI?2:0,
 reporter:[["html",{open:"never"}],["list"]],
 use:{
  baseURL:process.env.KUCHARZYNA_URL||"http://127.0.0.1:4173/",
  trace:"retain-on-failure",
  screenshot:"only-on-failure",
  video:"retain-on-failure",
  serviceWorkers:"block",
  locale:"pl-PL",
  timezoneId:"Europe/Warsaw"
 },
 webServer:{
  command:"python3 -m http.server 4173 --bind 127.0.0.1",
  url:"http://127.0.0.1:4173/",
  reuseExistingServer:!process.env.CI,
  timeout:15000
 },
 projects:[{
  name:"iphone",
  use:{
   ...devices["iPhone 15 Pro Max"],
   browserName:"webkit",
   viewport:{width:440,height:956},
   deviceScaleFactor:3,
   isMobile:true,
   hasTouch:true
  }
 }]
});